#pragma once

// =============================================================================
//  THE CONTRACT
// =============================================================================
//
//  This is the only file the course and your game agree on.
//
//  You write a class that inherits from ttt::Game, and a function called
//  ttt::createGame() that hands one back. That is the whole agreement.
//
//  Everything else -- your class names, your member names, your file names,
//  how you store the board, how you decide whose turn it is -- is yours.
//  The course never looks at it and never asks.
//
//  Do not edit this file. The tests and the web server both depend on it
//  looking exactly like this.
//
// =============================================================================

#include <array>
#include <memory>
#include <optional>

namespace ttt {

inline constexpr int kCellCount = 9;

// What is sitting in one square of the board.
enum class Mark { Empty, X, O };

// Who is playing.
enum class Player { X, O };

// Where the whole game is right now.
enum class Status { InProgress, Won, Draw };

// Why a move was refused. `None` means it was accepted.
enum class MoveError {
    None,        // the move was played
    OutOfRange,  // the cell number was not 0..8
    CellTaken,   // something is already in that cell
    GameOver     // the game has already finished
};

// A complete picture of the game at one instant.
//
// Cells are numbered 0..8, reading left-to-right, top-to-bottom:
//
//      0 | 1 | 2
//     ---+---+---
//      3 | 4 | 5
//     ---+---+---
//      6 | 7 | 8
//
// (The web page shows 1..9 to the human, because humans count from 1.
//  That conversion happens where the human is looking, and nowhere else.)
struct Snapshot {
    std::array<Mark, kCellCount> board{};
    Player                       turn   = Player::X;
    Status                       status = Status::InProgress;
    std::optional<Player>        winner{};  // only set when status == Won
};

// What happened when someone tried to move.
struct MoveResult {
    MoveError error = MoveError::None;
    Snapshot  snapshot{};

    bool ok() const { return error == MoveError::None; }
};

// The one thing the course needs your game to be.
//
// You will write something like:
//
//     class MyGame : public ttt::Game {
//     public:
//         ttt::Snapshot   snapshot() const override { ... }
//         ttt::MoveResult play(int cell)   override { ... }
//         void            reset()          override { ... }
//     };
//
class Game {
public:
    virtual ~Game() = default;

    // A picture of the game right now. Must not change the game.
    virtual Snapshot snapshot() const = 0;

    // Try to play `cell` for whoever's turn it is.
    // Always returns a fresh snapshot, whether the move worked or not.
    virtual MoveResult play(int cell) = 0;

    // Back to an empty board, X to play.
    virtual void reset() = 0;
};

// You write this. The course calls it.
//
// This free function is the *only* name the course knows about your code.
// That is deliberate: it lets the tests and the web server reach your game
// without knowing a single one of your class or file names.
std::unique_ptr<Game> createGame();

}  // namespace ttt
